apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo
  description: demo
  links:
    - url: https://api-test-backstagedemo.empcbr.thoughtworks-labs.net/swagger
      title: test
      icon: dashboard
  annotations:
    circleci.com/project-slug: github/platform-dx/demo-test-ea58565
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug:  platform-dx/demo-test-ea58565
    sonarqube.org/project-key: "test"
    backstage.io/kubernetes-label-selector: "app=test"
    backstage.io/adr-location: docs/adrs/
spec:
  type: service
  lifecycle: experimental
  owner: test
