apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test"
  description: "test"
  links:
    - url: https://api-test-backstagedemo.empcbr.thoughtworks-labs.net/swagger
      title: test
      icon: dashboard
  annotations:
    circleci.com/project-slug: github/platform-dx/demo-test-ea58565
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug:  platform-dx/demo-test-ea58565
    sonarqube.org/project-key: "test"
    backstage.io/kubernetes-label-selector: "app=test"
    backstage.io/adr-location: docs/adrs/
spec:
  type: service
  lifecycle: experimental
  owner: "test"
  providesApis:
    - "test"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: test-api
  description: test api
spec:
  type: openapi
  lifecycle: experimental
definition: |
  openapi: "3.0.1"
  info:
    version: 1.0.0
    title: test - api
  servers:
    - url: https://api-test-backstagedemo.empcbr.thoughtworks-labs.net
  paths:
    /Math:
      get:
        summary: Sum given numbers
        tags:
          - Math
        parameters:
          - name: firstNumber
            in: query
            schema:
              type: integer
              format: int32
          - name: secondNumber
            in: query
            schema:
              type: integer
              format: int32
        responses:
          '200':
            description: Success
            content:
              text/plain:
                schema:
                  type: integer
                  format: int32
              application/json:
                schema:
                  type: integer
                  format: int32
              text/json:
                schema:
                  type: integer
                  format: int32
          
  
